version: '3'
services:
  go-web-app:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - VIRTUAL_HOST=huntermotko.dev
      - LETSENCRYPT_HOST=huntermotko.dev
